using SipAndStayCafe.Domain.Common;

namespace SipAndStayCafe.Domain.Entities;

public sealed class Table : BaseEntity
{
    /// <summary>
    /// Human-readable table identifier shown to customers and staff (e.g. 1, 2, 12).
    /// Unique within the cafe. Used as the display label on the cashier and kitchen screens.
    /// </summary>
    public int TableNumber { get; set; }

    /// <summary>
    /// The full URL encoded into the QR code for this table.
    /// Format: <c>https://&lt;domain&gt;/menu?table=&lt;TableNumber&gt;</c>.
    /// Generated by the QRCoder integration and stored here so it can be
    /// re-printed without regeneration.
    /// </summary>
    public string QRCodeUrl { get; set; } = string.Empty;

    /// <summary>
    /// When <c>false</c>, the table is deactivated (e.g. closed for maintenance).
    /// Scanning its QR code will show an "unavailable" message to the customer.
    /// </summary>
    public bool IsActive { get; set; } = true;

    // -----------------------------------------------------------------------
    // Navigation
    // -----------------------------------------------------------------------

    /// <summary>
    /// All sessions that have ever been opened at this table, ordered by time.
    /// Only one session will have <see cref="TableSession.ClosedAt"/> == null at any time.
    /// </summary>
    public List<TableSession> Sessions { get; private set; } = [];
}
