using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SipAndStayCafe.Domain.Common
{
    /// <summary>
    /// Base class for all persisted domain entities.
    /// Provides a strongly-typed <see cref="Guid"/> primary key and
    /// audit timestamps that are managed by <c>AppDbContext</c> before
    /// every save — application code should never set them manually.
    /// </summary>
    public abstract class BaseEntity
    {
        /// <summary>
        /// Globally unique identifier for this entity.
        /// Generated by the database (gen_random_uuid()) via EF Core value generation.
        /// </summary>
        public Guid Id { get; init; } = Guid.NewGuid();

        /// <summary>
        /// UTC timestamp of when the record was first persisted.
        /// Set automatically in <c>AppDbContext.SaveChangesAsync</c> on <c>Added</c> state.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// UTC timestamp of the most recent update to the record.
        /// Set automatically in <c>AppDbContext.SaveChangesAsync</c> on <c>Modified</c> state.
        /// </summary>
        public DateTime UpdatedAt { get; set; }
    }
}
